name: The New Era Museum Grid
favicon: null
layout_spectrum: 0.75099
typography_spectrum: 0.28747
title: The New Era Museum Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#674853'
    - '#ffffff'
    - '#b1b28d'
    - '#736258'
    - '#9d9181'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.749537359457463
  rhythmicContrast: 0.25
purpose: []
