name: nem
favicon: null
layout_spectrum: 0.2452106336131692
typography_spectrum: 0.26051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#674853'
    - '#ffffff'
    - '#b1b28d'
    - '#736258'
    - '#9d9181'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.749537359457463
  rhythmicContrast: 0.1735142022371292
purpose: []
