typography_spectrum: 0.28996
color:
  brandColors:
    - '#674853'
    - '#ffffff'
    - '#b1b28d'
    - '#736258'
    - '#9d9181'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.749537359457463
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48822
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: The New Era Museum
  email: theneweramuseum@gmail.com
  url: 'http://neweramuseum.org'
name: The New Era Museum Grid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The New Era Museum Grid
purpose: []
