typography_spectrum: 0.5623946
color:
  brandStrength: 0.06761277676559985
  saturation: 0.07454189308919013
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  lightness: 0.09618587675504386
  rhythmicContrast: 0.967965091811493
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7006745
analytics:
  facebook: null
  google: null
  twitter: null
author:
  url: 'http://neweramuseum.org'
  name: The New Era Museum
  email: theneweramuseum@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/04bb5f9d-12a3-4dd9-99fd-a05a759ea80d.jpg
name: The New Era Museum Grid
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/22b7046d-ed0f-4c09-b780-42479e2d2af2.jpg
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The New Era Museum Grid
description: '"Your photo could change the reality."'
purpose: []
